---
- name: Harden server
  hosts: kpei
  become: true
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding, required by Docker engine
      net.ipv4.ip_forward: 1
