---
collections:
  - name: google.cloud
    version: 1.3.0
  - name: devsec.hardening
    version: 9.0.1
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.2.0

roles:
  - name: geerlingguy.docker
    version: 7.1.0
